# pyproject.toml

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["timeview"]

[project]
name = "TIMEVIEW"
version = "1.0.0"
readme = "README.md"
dependencies = []
